// AudioTech product catalog data
window.PRODUCTS = [
  {
    id: 1,
    name: "HATOR Hyperpunk 3X (ESH14)",
    price: 50.51,
    image: "./images/hator-3x.webp",
    shortDesc: "Wireless tri-mode gaming headset with punchy bass.",
    description:
      "The HATOR Hyperpunk 3X is a versatile tri-mode gaming headset that connects via 2.4GHz wireless, Bluetooth, or USB cable. Its 50mm drivers deliver punchy bass and clear mids, while the lightweight frame keeps you comfortable during marathon sessions.",
    features: [
      "Tri-mode connection: 2.4GHz, Bluetooth 5.3, wired USB",
      "50mm dynamic drivers with deep bass response",
      "Detachable noise-cancelling microphone",
      "Up to 40 hours of battery life",
    ],
    specs: {
      "Driver size": "50 mm",
      Connection: "2.4GHz / Bluetooth 5.3 / USB",
      "Battery life": "Up to 40 hours",
      "Frequency response": "20 Hz - 20 kHz",
      Microphone: "Detachable, noise-cancelling",
      Weight: "310 g",
    },
    rating: 4.7,
    reviews: [
      {
        name: "Alex Carter",
        rating: 5,
        date: "2026-05-14",
        text: "Great value for a tri-mode headset. The wireless connection is rock solid and battery easily lasts a week of gaming.",
      },
      {
        name: "Maria Gonzalez",
        rating: 5,
        date: "2026-04-02",
        text: "Bass is punchy without drowning the mids. Very comfortable even with glasses on.",
      },
      {
        name: "Tom Reed",
        rating: 4,
        date: "2026-02-19",
        text: "Solid headset for the price. The mic is decent but could be a bit clearer in noisy rooms.",
      },
    ],
  },
  {
    id: 2,
    name: "Logitech G325",
    price: 50.45,
    image: "./images/logitech-g325.webp",
    shortDesc: "Lightweight wired headset with clear, balanced sound.",
    description:
      "The Logitech G325 is a lightweight wired gaming headset built for everyday play. Its 40mm drivers produce clear, balanced audio, and the flip-to-mute microphone makes jumping between game chat and real life effortless.",
    features: [
      "Lightweight design at just 260 g",
      "40mm drivers with balanced sound signature",
      "Flip-to-mute microphone",
      "3.5mm jack works with PC, consoles and mobile",
    ],
    specs: {
      "Driver size": "40 mm",
      Connection: "Wired 3.5mm",
      "Cable length": "2 m",
      "Frequency response": "20 Hz - 20 kHz",
      Microphone: "Flip-to-mute boom",
      Weight: "260 g",
    },
    rating: 4.5,
    reviews: [
      {
        name: "Jake Miller",
        rating: 5,
        date: "2026-05-30",
        text: "Simple, light and it just works on everything I own. Perfect no-fuss headset.",
      },
      {
        name: "Emily Watson",
        rating: 4,
        date: "2026-03-22",
        text: "Comfortable for long calls and gaming. Not the deepest bass, but the clarity is excellent.",
      },
      {
        name: "Chris Doyle",
        rating: 4,
        date: "2026-01-15",
        text: "Good build quality for the price. The flip-to-mute mic is super handy.",
      },
    ],
  },
  {
    id: 3,
    name: "Razer BlackShark V2",
    price: 96.45,
    image: "./images/razer-blackshark.webp",
    shortDesc: "Esports headset with THX Spatial Audio and TriForce drivers.",
    description:
      "The Razer BlackShark V2 is built for competitive play. Razer TriForce Titanium 50mm drivers separate highs, mids and lows for pinpoint positional audio, while THX Spatial Audio delivers a true competitive edge in FPS titles.",
    features: [
      "Razer TriForce Titanium 50mm drivers",
      "THX Spatial Audio for precise positioning",
      "HyperClear cardioid microphone",
      "Advanced passive noise cancellation",
    ],
    specs: {
      "Driver size": "50 mm TriForce Titanium",
      Connection: "Wired 3.5mm + USB sound card",
      "Frequency response": "12 Hz - 28 kHz",
      Microphone: "HyperClear cardioid, detachable",
      "Ear cushions": "FlowKnit memory foam",
      Weight: "262 g",
    },
    rating: 4.8,
    reviews: [
      {
        name: "Dmitry Volkov",
        rating: 5,
        date: "2026-06-08",
        text: "Footsteps in shooters are crystal clear. Best positional audio I have used at this price.",
      },
      {
        name: "Sophie Lane",
        rating: 5,
        date: "2026-04-27",
        text: "Extremely light and comfortable. The mic sounds almost broadcast quality with the USB card.",
      },
      {
        name: "Ben Ashford",
        rating: 4,
        date: "2026-02-03",
        text: "Great headset overall. Wish the cable was detachable, but the sound makes up for it.",
      },
    ],
  },
  {
    id: 4,
    name: "Hator Hypergang",
    price: 80.45,
    image: "./images/hator-hypergang.webp",
    shortDesc: "Studio-grade sound in a rugged gaming build.",
    description:
      "The Hator Hypergang combines studio-grade acoustics with a rugged all-metal headband. Large 53mm drivers push detailed, wide soundstage audio, making it equally at home in games, music and movies.",
    features: [
      "53mm drivers with wide soundstage",
      "All-metal reinforced headband",
      "Breathable protein leather ear cushions",
      "In-line remote with volume and mic controls",
    ],
    specs: {
      "Driver size": "53 mm",
      Connection: "Wired 3.5mm",
      "Frequency response": "15 Hz - 25 kHz",
      Microphone: "Detachable boom",
      Impedance: "32 Ohm",
      Weight: "340 g",
    },
    rating: 4.6,
    reviews: [
      {
        name: "Olga Petrenko",
        rating: 5,
        date: "2026-05-11",
        text: "Sound is surprisingly wide and detailed. Feels like headphones twice the price.",
      },
      {
        name: "Ryan Cole",
        rating: 4,
        date: "2026-03-18",
        text: "Very sturdy build. Slightly heavy after 4+ hours but the sound is worth it.",
      },
      {
        name: "Nina Berg",
        rating: 5,
        date: "2026-01-29",
        text: "Bought it for gaming, kept it for music. Excellent all-rounder.",
      },
    ],
  },
  {
    id: 5,
    name: "Hator Phoenix",
    price: 100.45,
    image: "./images/hator-phoenix.webp",
    shortDesc: "Flagship wired headset with hi-res certified audio.",
    description:
      "The Hator Phoenix is the flagship of the lineup, featuring hi-res certified 53mm drivers and premium memory foam cushions. Designed for players who refuse to compromise between comfort and audio fidelity.",
    features: [
      "Hi-Res certified 53mm drivers",
      "Premium memory foam ear cushions",
      "Braided detachable cable",
      "Compatible with PC, PS5, Xbox and mobile",
    ],
    specs: {
      "Driver size": "53 mm Hi-Res",
      Connection: "Wired 3.5mm, detachable cable",
      "Frequency response": "10 Hz - 40 kHz",
      Microphone: "Detachable, omnidirectional",
      Impedance: "32 Ohm",
      Weight: "355 g",
    },
    rating: 4.7,
    reviews: [
      {
        name: "Lucas Meyer",
        rating: 5,
        date: "2026-06-01",
        text: "The hi-res drivers really shine with lossless audio. Fantastic detail across the range.",
      },
      {
        name: "Anna Kowalski",
        rating: 5,
        date: "2026-04-09",
        text: "Most comfortable headset I have owned. The memory foam is a game changer.",
      },
      {
        name: "Victor Hale",
        rating: 4,
        date: "2026-02-14",
        text: "Excellent sound, premium feel. A carrying case would have been a nice bonus.",
      },
    ],
  },
  {
    id: 6,
    name: "Logitech G325 Gaming",
    price: 95,
    image: "./images/logitech-g325-gaming.webp",
    shortDesc: "Tuned gaming edition with enhanced bass and comfort.",
    description:
      "The Logitech G325 Gaming edition takes the classic G325 formula and tunes it for immersion: enhanced bass response, plusher memory foam pads and a redesigned boom mic for clearer team communication.",
    features: [
      "Gaming-tuned 40mm drivers with enhanced bass",
      "Plush memory foam ear pads",
      "Redesigned noise-isolating boom mic",
      "Multi-platform 3.5mm connectivity",
    ],
    specs: {
      "Driver size": "40 mm",
      Connection: "Wired 3.5mm",
      "Frequency response": "20 Hz - 20 kHz",
      Microphone: "Noise-isolating boom",
      "Cable length": "2 m",
      Weight: "275 g",
    },
    rating: 4.5,
    reviews: [
      {
        name: "Peter Novak",
        rating: 5,
        date: "2026-05-20",
        text: "The bass boost makes explosions feel massive. Great immersive tuning.",
      },
      {
        name: "Sara Kim",
        rating: 4,
        date: "2026-03-05",
        text: "Comfy pads and a clear mic. Everything a team player needs.",
      },
      {
        name: "Ivan Horak",
        rating: 4,
        date: "2026-01-22",
        text: "Solid upgrade over the base G325 if you like stronger bass.",
      },
    ],
  },
  {
    id: 7,
    name: "Razer Blackshark V3",
    price: 50.62,
    image: "./images/razer-v3.webp",
    shortDesc: "Next-gen esports acoustics at an accessible price.",
    description:
      "The Razer Blackshark V3 brings next-generation esports acoustics to an accessible price point. Improved passive isolation and a refined driver tuning keep you locked into the game with zero distractions.",
    features: [
      "Refined 50mm drivers with esports tuning",
      "Improved passive noise isolation",
      "Lightweight 250g frame",
      "Cross-platform 3.5mm compatibility",
    ],
    specs: {
      "Driver size": "50 mm",
      Connection: "Wired 3.5mm",
      "Frequency response": "12 Hz - 28 kHz",
      Microphone: "Fixed boom, noise-cancelling",
      "Ear cushions": "Breathable memory foam",
      Weight: "250 g",
    },
    rating: 4.6,
    reviews: [
      {
        name: "Felix Braun",
        rating: 5,
        date: "2026-06-12",
        text: "Unreal value. Sounds very close to the V2 at nearly half the price.",
      },
      {
        name: "Julia Romero",
        rating: 4,
        date: "2026-04-15",
        text: "Light as a feather, great isolation. Mic is fixed but sounds clean.",
      },
      {
        name: "Marcus Webb",
        rating: 5,
        date: "2026-02-27",
        text: "My go-to recommendation for anyone starting competitive FPS.",
      },
    ],
  },
  {
    id: 8,
    name: "Logitech G321 Lightspeed Black",
    price: 73.48,
    image: "./images/logitech-g321.webp",
    shortDesc: "Wireless Lightspeed freedom with 20-hour battery.",
    description:
      "The Logitech G321 Lightspeed cuts the cord with Logitech's pro-grade Lightspeed wireless technology. Enjoy up to 20 hours of lag-free audio, a comfortable suspension headband and reliable range up to 15 meters.",
    features: [
      "Lightspeed 2.4GHz pro-grade wireless",
      "Up to 20 hours of battery life",
      "Suspension headband design",
      "15m wireless range",
    ],
    specs: {
      "Driver size": "40 mm",
      Connection: "Lightspeed 2.4GHz wireless",
      "Battery life": "Up to 20 hours",
      Range: "15 m",
      Microphone: "Flip-to-mute boom",
      Weight: "290 g",
    },
    rating: 4.4,
    reviews: [
      {
        name: "Hannah Lee",
        rating: 5,
        date: "2026-05-25",
        text: "Zero lag, zero dropouts. The freedom of wireless without any compromise.",
      },
      {
        name: "Oscar Lindqvist",
        rating: 4,
        date: "2026-03-30",
        text: "Battery comfortably lasts several long sessions. Charging is quick too.",
      },
      {
        name: "Derek Stone",
        rating: 4,
        date: "2026-02-08",
        text: "Comfortable suspension band. Sound is good, though highs can be a bit sharp.",
      },
    ],
  },
  {
    id: 9,
    name: "Logitech G735 Wireless Gaming Headset OFF WHITE",
    price: 149.29,
    image: "./images/logitech-g735.webp",
    shortDesc: "Aurora Collection headset with dual wireless and RGB.",
    description:
      "Part of the Aurora Collection, the Logitech G735 pairs a soft, cloud-like design with serious tech: dual wireless (Lightspeed + Bluetooth), customizable LIGHTSYNC RGB and up to 56 hours of playtime with lighting off.",
    features: [
      "Dual connectivity: Lightspeed + Bluetooth",
      "LIGHTSYNC RGB customizable lighting",
      "Up to 56 hours battery (RGB off)",
      "Designed for smaller head sizes and comfort",
    ],
    specs: {
      "Driver size": "40 mm",
      Connection: "Lightspeed 2.4GHz / Bluetooth / 3.5mm",
      "Battery life": "Up to 56 hours (RGB off)",
      Lighting: "LIGHTSYNC RGB",
      Microphone: "Detachable boom + built-in",
      Weight: "273 g",
    },
    rating: 4.7,
    reviews: [
      {
        name: "Mia Chen",
        rating: 5,
        date: "2026-06-04",
        text: "Gorgeous design and the fit is perfect for me. Finally a headset that does not clamp.",
      },
      {
        name: "Laura Smith",
        rating: 5,
        date: "2026-04-19",
        text: "Dual wireless is so convenient - game audio and phone calls at the same time.",
      },
      {
        name: "Kate Turner",
        rating: 4,
        date: "2026-02-23",
        text: "Battery life is incredible. RGB is pretty but drains it faster, as expected.",
      },
    ],
  },
  {
    id: 10,
    name: "Logitech Lightspeed Wireless RGB Gaming Headset G733 Blue",
    price: 199.82,
    image: "./images/logi-g733-blue.webp",
    shortDesc: "Ultra-light wireless RGB headset in bold blue.",
    description:
      "The Logitech G733 in bold blue weighs just 278g and delivers Lightspeed wireless with up to 29 hours of battery. PRO-G drivers and Blue VO!CE mic filters give you both immersive sound and a broadcast-quality voice.",
    features: [
      "Ultra-light 278g design",
      "Lightspeed wireless, 20m range",
      "Blue VO!CE microphone technology",
      "Front-facing LIGHTSYNC RGB lighting",
    ],
    specs: {
      "Driver size": "40 mm PRO-G",
      Connection: "Lightspeed 2.4GHz wireless",
      "Battery life": "Up to 29 hours",
      Range: "20 m",
      Microphone: "Detachable, Blue VO!CE",
      Weight: "278 g",
    },
    rating: 4.6,
    reviews: [
      {
        name: "Noah Fischer",
        rating: 5,
        date: "2026-05-17",
        text: "The blue colorway looks amazing on stream. Mic filters make my voice sound professional.",
      },
      {
        name: "Grace Palmer",
        rating: 4,
        date: "2026-03-26",
        text: "Suspension strap plus light weight means I forget I am wearing it.",
      },
      {
        name: "Leo Martins",
        rating: 5,
        date: "2026-01-31",
        text: "Best wireless headset I have tried. The PRO-G drivers are clean and punchy.",
      },
    ],
  },
  {
    id: 11,
    name: "Logitech Lightspeed Wireless RGB Gaming Headset G733 White",
    price: 199.82,
    image: "./images/logi-g733-white-rgb.webp",
    shortDesc: "Ultra-light wireless RGB headset in clean white.",
    description:
      "The G733 in clean white brings the same ultra-light Lightspeed wireless experience with a minimalist look. PRO-G drivers, 29-hour battery and vibrant front-facing RGB make it a centerpiece of any white setup.",
    features: [
      "Ultra-light 278g design",
      "Lightspeed wireless, 20m range",
      "Blue VO!CE microphone technology",
      "Front-facing LIGHTSYNC RGB lighting",
    ],
    specs: {
      "Driver size": "40 mm PRO-G",
      Connection: "Lightspeed 2.4GHz wireless",
      "Battery life": "Up to 29 hours",
      Range: "20 m",
      Microphone: "Detachable, Blue VO!CE",
      Weight: "278 g",
    },
    rating: 4.6,
    reviews: [
      {
        name: "Isabella Rossi",
        rating: 5,
        date: "2026-06-10",
        text: "Matches my white desk setup perfectly. Sound and comfort are top tier.",
      },
      {
        name: "Ethan Brooks",
        rating: 4,
        date: "2026-04-05",
        text: "Great headset. White pads need occasional cleaning but look fantastic.",
      },
      {
        name: "Chloe Adams",
        rating: 5,
        date: "2026-02-16",
        text: "Light, wireless, gorgeous RGB. Everything I wanted.",
      },
    ],
  },
  {
    id: 12,
    name: "Logitech Lightspeed Wireless RGB Gaming Headset G733 Lilac",
    price: 200,
    image: "./images/logi-rgb-g733-lical.webp",
    shortDesc: "Ultra-light wireless RGB headset in playful lilac.",
    description:
      "The G733 Lilac adds a playful pop of color to Logitech's ultra-light wireless formula. Same PRO-G audio, same 29-hour battery, same Lightspeed reliability - now in a standout lilac finish.",
    features: [
      "Ultra-light 278g design",
      "Lightspeed wireless, 20m range",
      "Blue VO!CE microphone technology",
      "Front-facing LIGHTSYNC RGB lighting",
    ],
    specs: {
      "Driver size": "40 mm PRO-G",
      Connection: "Lightspeed 2.4GHz wireless",
      "Battery life": "Up to 29 hours",
      Range: "20 m",
      Microphone: "Detachable, Blue VO!CE",
      Weight: "278 g",
    },
    rating: 4.7,
    reviews: [
      {
        name: "Zoe Nakamura",
        rating: 5,
        date: "2026-05-28",
        text: "The lilac color is even prettier in person. Performs exactly like my friend's black G733.",
      },
      {
        name: "Ava Johnson",
        rating: 5,
        date: "2026-03-14",
        text: "Comfortable for all-day wear and the RGB matches my keyboard perfectly.",
      },
      {
        name: "Ruby Clark",
        rating: 4,
        date: "2026-01-19",
        text: "Love it. Only wish the mic was slightly longer, otherwise flawless.",
      },
    ],
  },
  {
    id: 13,
    name: "Razer Blackshark V2 PRO 2023 White",
    price: 201.66,
    image: "./images/razer-blackshark-white.webp",
    shortDesc: "Pro esports wireless headset with 70-hour battery.",
    description:
      "The Razer Blackshark V2 PRO 2023 is the choice of esports professionals. HyperSpeed wireless, TriForce Titanium 50mm drivers and a wideband HyperClear mic deliver tournament-grade performance for up to 70 hours per charge.",
    features: [
      "Razer HyperSpeed low-latency wireless",
      "TriForce Titanium 50mm drivers",
      "Wideband HyperClear Super Mic",
      "Up to 70 hours of battery life",
    ],
    specs: {
      "Driver size": "50 mm TriForce Titanium",
      Connection: "HyperSpeed 2.4GHz / Bluetooth 5.2",
      "Battery life": "Up to 70 hours",
      "Frequency response": "12 Hz - 28 kHz",
      Microphone: "Detachable HyperClear Super Wideband",
      Weight: "320 g",
    },
    rating: 4.8,
    reviews: [
      {
        name: "Daniel Frost",
        rating: 5,
        date: "2026-06-15",
        text: "Tournament-level audio. The 70-hour battery is not marketing - it truly lasts weeks.",
      },
      {
        name: "Yuki Tanaka",
        rating: 5,
        date: "2026-04-22",
        text: "The wideband mic is the best I have heard on any wireless headset, period.",
      },
      {
        name: "Adam Kessler",
        rating: 4,
        date: "2026-03-01",
        text: "Premium price but pro quality. The white finish stays clean better than expected.",
      },
    ],
  },
  {
    id: 14,
    name: "Hator Hyperpunk 3 Wireless White",
    price: 52.81,
    image: "./images/hator-white.webp",
    shortDesc: "Affordable wireless freedom in a crisp white finish.",
    description:
      "The Hator Hyperpunk 3 Wireless in white delivers reliable 2.4GHz wireless and Bluetooth connectivity at an accessible price. A crisp white finish, 40-hour battery and comfortable oval ear cups make it an everyday favorite.",
    features: [
      "Dual mode: 2.4GHz wireless + Bluetooth 5.3",
      "Up to 40 hours of battery life",
      "Crisp white finish with matte texture",
      "Comfortable oval memory foam ear cups",
    ],
    specs: {
      "Driver size": "50 mm",
      Connection: "2.4GHz / Bluetooth 5.3",
      "Battery life": "Up to 40 hours",
      "Frequency response": "20 Hz - 20 kHz",
      Microphone: "Detachable, flexible boom",
      Weight: "300 g",
    },
    rating: 4.5,
    reviews: [
      {
        name: "Elena Sokolova",
        rating: 5,
        date: "2026-05-08",
        text: "Wireless this good at this price feels illegal. Battery life is outstanding.",
      },
      {
        name: "Paul Whitman",
        rating: 4,
        date: "2026-03-12",
        text: "Clean look, solid connection. Ear cups are roomy and comfortable.",
      },
      {
        name: "Tina Moore",
        rating: 4,
        date: "2026-01-25",
        text: "Very happy with it. Switching between PC and phone via Bluetooth is seamless.",
      },
    ],
  },
  {
    id: 15,
    name: "Hator Hyperpunk 3 Wireless Cyber Violet (ESH19)",
    price: 52.81,
    image: "./images/hator-vaiolet.webp",
    shortDesc: "Dual-mode wireless headset in a striking violet finish.",
    description:
      "The Hyperpunk 3 Wireless in Cyber Violet stands out with a bold finish while keeping the specs that matter: dual-mode wireless, 40-hour battery and 50mm drivers tuned for gaming and music alike.",
    features: [
      "Dual mode: 2.4GHz wireless + Bluetooth 5.3",
      "Up to 40 hours of battery life",
      "Striking Cyber Violet finish",
      "50mm drivers tuned for games and music",
    ],
    specs: {
      "Driver size": "50 mm",
      Connection: "2.4GHz / Bluetooth 5.3",
      "Battery life": "Up to 40 hours",
      "Frequency response": "20 Hz - 20 kHz",
      Microphone: "Detachable, flexible boom",
      Weight: "300 g",
    },
    rating: 4.6,
    reviews: [
      {
        name: "Vera Lisova",
        rating: 5,
        date: "2026-06-06",
        text: "The violet color is stunning and the sound punches way above the price tag.",
      },
      {
        name: "Sam Porter",
        rating: 4,
        date: "2026-04-11",
        text: "Bought it for the looks, stayed for the battery life. Really solid headset.",
      },
      {
        name: "Kira Volkova",
        rating: 5,
        date: "2026-02-20",
        text: "Perfect match for my purple setup. Comfortable and reliable wireless.",
      },
    ],
  },
  {
    id: 16,
    name: "HATOR Hypergang 3 USB Black (ESH50)",
    price: 45.92,
    image: "./images/hypergang-3-usb-black_1.png",
    shortDesc: "USB headset with virtual 7.1 surround sound.",
    description:
      "The HATOR Hypergang 3 USB brings virtual 7.1 surround sound to your desk with a simple plug-and-play USB connection. RGB accents, on-ear controls and a flexible mic make it a complete package for PC gamers.",
    features: [
      "Virtual 7.1 surround sound",
      "Plug-and-play USB connection",
      "RGB lighting accents",
      "On-ear volume and mic controls",
    ],
    specs: {
      "Driver size": "50 mm",
      Connection: "Wired USB",
      Surround: "Virtual 7.1",
      "Frequency response": "20 Hz - 20 kHz",
      Microphone: "Flexible, omnidirectional",
      Weight: "325 g",
    },
    rating: 4.4,
    reviews: [
      {
        name: "Greg Olsen",
        rating: 5,
        date: "2026-05-03",
        text: "7.1 surround at this price is a steal. Positional audio in games is impressive.",
      },
      {
        name: "Lena Fedorova",
        rating: 4,
        date: "2026-03-08",
        text: "Simple USB setup, no drivers needed. Good mic for calls and chat.",
      },
      {
        name: "Josh Barnes",
        rating: 4,
        date: "2026-01-12",
        text: "Great entry-level surround headset. RGB is subtle, which I prefer.",
      },
    ],
  },
];

window.getProductById = function (id) {
  return window.PRODUCTS.find((p) => p.id === Number(id));
};

window.formatPrice = function (price) {
  return "$" + price.toFixed(2);
};
